-- OPERADORES ARITMETICOS
-- OPERADOR +
SELECT 1 + 3 AS RESULTADO;

-- OPERADOR * 
SELECT 2 * 3 AS RESULTADO;

-- OPERADOR - 
SELECT 5 - 2 AS RESULTADO;

-- OPERADOR /
SELECT 15 / 3 AS RESULTADO;

-- OPERADOR %
SELECT 12%5 AS RESULTADO;

-- OPERADOR %, SOBRA ZERO
SELECT 12%4 AS RESULTADO;

-- EXPRESSÓES

SELECT ((1+4) * (3*3))/5 AS RESULTADO;

/*
USANDO O OPERADOR DE ADIÇÃO PARA CALCULAR O NÚMERO TOTAL DE
HORAS DE AUSÊNCIA DO TRABALHO PARA CADA FUNCIONÁRIO
*/

USE AdventureWorks2017;

SELECT P.FIRSTNAME,
	   P.LASTNAME,
	   E.VACATIONHOURS,
	   E.SICKLEAVEHOURS,
	   E.VACATIONHOURS + E.SICKLEAVEHOURS AS 'HORAS AUSENTE'
FROM HumanResources.Employee AS E
	JOIN Person.Person AS P
	ON E.BusinessEntityID = P.BusinessEntityID
	ORDER BY 'HORAS AUSENTE' ASC;

-- USANDO SUBTRAÇÃO EM UMA INSTRUÇÃO SELECT
SELECT MAX(TAXRATE) MAXIMO,
       MIN(TAXRATE) MINIMO,
	   MAX(TAXRATE) - MIN(TAXRATE) AS 'DIFERENÇA DE TAXA'
FROM Sales.SalesTaxRate
WHERE StateProvinceID IS NOT NULL;

/*
O EXEMPLO A SEGUIR RECUPERA O NÚMERO DE IDENTIFICAÇÃO DO PRODUTO,
O NOME, O PREÇO DE TABELA E O NOVO PREÇO DE TABELA DE 
TODAS AS BICICLETAS MOUNTAIN BIKE NA TABELA PRODUCT.
O NOVO PREÇO DE TABELA É CALCULADO USANDO O  OPERADOR ARITMÉTICO * PARA 
MULTIPLICAR LISPRICE POR 1.15.
*/

SELECT PRODUCTID,
	   NAME,
	   LISTPRICE,
	   LISTPRICE * 1.15 AS NOVO_PRECO
FROM Production.Product
WHERE NAME LIKE 'Mountain-%'
ORDER BY ProductID ASC;

/*
O EXEMPLO A SEGUIR USA O OPERADOR ARIMÉTICO DE DIVISÃO PARA 
CALCULAR A META DE VENDAS MENSAL DA EQUIPE DE VENDAS EM CICLOS 
DE 12MESES
*/

SELECT S.BUSINESSENTITYID AS SALESPERSONID,
       P.FIRSTNAME,
	   P.LASTNAME,
	   S.SALESQUOTA,
	   S.SALESQUOTA / 12 AS 'META MENSAL',
	   E.JobTitle
FROM Sales.SalesPerson AS S
	JOIN HumanResources.Employee AS E
	ON S.BusinessEntityID = E.BusinessEntityID
	JOIN Person.Person AS P
	ON S.BusinessEntityID = P.BusinessEntityID
WHERE S.SalesQuota IS NOT NULL;

/*
O EXEMPLO A SEGUIR DIVIDE O NÚMERO 38 POR 5.
ISTO RESULTA EM 7 COMO A PARTE INTEIRA DO RESULTADO = 7
E DEMONSTRA COMO O MÓDULO RETORNA O RESTO DE 3.
*/
SELECT 38 / 5 AS INTEIRO,
       38 % 5 AS RESTANTE;