-- DDL CRIAÇÃO DA TABELA PARA EXERCICICOS
USE curso;
GO

CREATE TABLE FUNCIONARIOS(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SALARIO DECIMAL(10,2),
	SETOR VARCHAR(30)
);

-- DML SELECT
SELECT * 
FROM FUNCIONARIOS; 

SELECT NOME, SETOR
FROM FUNCIONARIOS;

SELECT NOME, SETOR AS DEPTO
FROM FUNCIONARIOS;

-- DML INSERT
INSERT INTO FUNCIONARIOS VALUES('Joao', 1000, ''),
							   ('Jose', 2000, ''),
							   ('Alexandre', 3000, '');
-- OU
INSERT INTO FUNCIONARIOS(NOME, SALARIO) VALUES ('Pedro', 1000);

-- DML UPDATE
UPDATE FUNCIONARIOS SET SALARIO = '1500'
WHERE ID = '1';

-- OU AUMENTANDO DE 50% SOBRE O SALARIO ATUAL
UPDATE FUNCIONARIOS SET SALARIO = SALARIO*1.5
WHERE ID = '1';

-- UPDATE COM MAIS UM CAMPO
UPDATE FUNCIONARIOS SET SALARIO = SALARIO * 1.5 , SETOR = 'TI'
WHERE ID <>'1';

-- DML DELETE
DELETE FUNCIONARIOS
WHERE ID = '1';