-- DDL : DATA DEFINITION LANGUAGE
USE curso;
GO

CREATE TABLE COLABORADOR
(
	MATRICULA     INT IDENTITY(1,1) NOT NULL,
	NOME          VARCHAR(50)       NOT NULL,
	SOBRENOME     VARCHAR(50)       NOT NULL,
	ENDERECO      VARCHAR(50)       NOT NULL,
	CIDADE        VARCHAR(50)       NOT NULL,
	PAIS          VARCHAR(25)       NOT NULL,
	DATA_NASC     DATE              NOT NULL CHECK(DATA_NASC < GETDATE()),
	DATA_CADASTRO DATETIME DEFAULT  GETDATE(),
	SITUACAO      CHAR(1) DEFAULT('A')
);

-- DDL CRIANDO TABELA COM CHAVE ESTRANGEIRA
CREATE TABLE SALARIO
(
	MATRICULA INT PRIMARY KEY NOT NULL,
	SALARIO   DECIMAL(10,2) NOT NULL CHECK(SALARIO>0),
	FOREIGN KEY(MATRICULA) REFERENCES COLABORADOR(MATRICULA)
);

-- CORRINDO ERRO PARA CRIAR TABELA SALARIO
-- DDL PARA ADICIONAR CHAVE PRIMARIA NA TAB COLABORADOR
ALTER TABLE COLABORADOR ADD PRIMARY KEY (MATRICULA);

-- DDL CRIAÇÃO DE TABELA COM CHAVE PRIMARIA
CREATE TABLE AUDIT_SALARIO
(
	TRANSACAO  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MATRICULA  INT               NOT NULL,
	DATA_TRANS DATETIME          NOT NULL,
	SAL_ANTIGO DECIMAL(10,2),
	SAL_NOVO   DECIMAL(10,2),
	USUARIO    VARCHAR(20)       NOT NULL
);

-- ADD CHAVE ESTRANGEIRA
ALTER TABLE AUDIT_SALARIO
ADD FOREIGN KEY (MATRICULA) REFERENCES COLABORADOR (MATRICULA);

-- TENTANDO EXCLUIR A TABELAS COLABORADOR 
DROP TABLE COLABORADOR;

-- DDL CRIAÇÃO DE INDEX
CREATE INDEX IX_FUNC1 ON COLABORADOR(DATA_NASC);
CREATE INDEX IX_FUNC2 ON COLABORADOR(CIDADE, PAIS);

-- ADICIONAR NOVO CAMPO NA TABELA
ALTER TABLE COLABORADOR ADD GENERO CHAR(1);

-- RENOMEANDO CAMPO DA TABELA
-- EXEC SP_RENAME 'TABELA_ORIGEM.CAMPO_ORIG', 'CAMPO_ORIG', 'COLUMN'
EXEC SP_RENAME 'COLABORADOR.ENDERECO', 'ENDER', 'COLUMN' 

-- ALTERANDO TIPO DA COLUNA
ALTER TABLE COLABORADOR ALTER COLUMN ENDER VARCHAR(30);

-- EXCLUINDO CAMPO DA COLUNA
ALTER TABLE COLABORADOR DROP COLUMN GENERO;

-- EXCLUINDO A CHAVE ESTRANGEIRA
ALTER TABLE SALARIO
DROP CONSTRAINT FK__SALARIO__MATRICU__1F98B2C1;

-- RENOMEANDO TABELA
-- EXEC SP_RENAME 'NOME_ANTIGO', 'NOME_NOVO'
EXEC SP_RENAME 'COLABORADOR', 'FUCN';

EXEC SP_RENAME 'FUCN', 'COLABORADOR';

-- DDL PARA CRIAR UM BANCO DE DADOS
CREATE DATABASE TESTE;

-- EXCLUINDO BANCO DE DADOS
DROP DATABASE TESTE;

-- EXCLUINDO TABELA
DROP TABLE SALARIO;

-- CRIAÇÃO DE VIEW
CREATE VIEW V_COLABORADOR
 AS 
 SELECT * FROM COLABORADOR;

 -- ALTERANDO A VIEW
 ALTER VIEW V_COLABORADOR
 AS
 SELECT MATRICULA, NOME FROM COLABORADOR;

 -- EXCLUINDO A VIEW
 DROP VIEW V_COLABORADOR;

 -- EXCLUINDO INDEX
 DROP INDEX IX_FUNC1 ON COLABORADOR;

 -- CRIANDO INDEX
 CREATE INDEX IX_FUNC1 ON COLABORADOR (NOME);

 -- DDL TRUNCATE
 SELECT * INTO SENSO_BK FROM SENSO;

 -- VERIFICANDO DADOS
 SELECT * FROM SENSO_BK;

 -- REALIZANDO TRUNCATE
 TRUNCATE TABLE SENSO_BK;

 -- DDL TRUNCATE VERIFICADO
  SELECT * FROM SENSO_BK;


  --FAZENDO BK EM TABLEA TEMPORARIA
  SELECT * INTO #BK_SENSO2 FROM SENSO;

  -- VERIFICANDO REGISTROS TABELA TEMPORARIA
  SELECT * FROM #BK_SENSO2;

  -- ANALISE DE REGISTROS ANTES DO TRUNCATE
  SELECT COUNT(*) AS ANTES_TRUNCATE_COUNT
  FROM #BK_SENSO2;

  -- DDL TRUNCATE APAGAR DADOS DA TABELA
  TRUNCATE TABLE SENSO;

  -- VERIFICANDO TABELAS APOS TRUNCATE
   SELECT COUNT(*) AS DEPOIS_TRUNCATE_COUNT
  FROM SENSO;

  -- POPULANDO A TABELA COM DADOS DA TABELA TEMPORARIA
  INSERT INTO SENSO
  SELECT * FROM #BK_SENSO2

  -- VERIFICANDO REGISTROS
  SELECT * FROM SENSO;