-- DDL : DATA DEFINITION LANGUAGE
USE curso;
GO

CREATE TABLE COLABORADOR
(
	MATRICULA     INT IDENTITY(1,1) NOT NULL,
	NOME          VARCHAR(50)       NOT NULL,
	SOBRENOME     VARCHAR(50)       NOT NULL,
	ENDERECO      VARCHAR(50)       NOT NULL,
	CIDADE        VARCHAR(50)       NOT NULL,
	PAIS          VARCHAR(25)       NOT NULL,
	DATA_NASC     DATE              NOT NULL CHECK(DATA_NASC < GETDATE()),
	DATA_CADASTRO DATETIME DEFAULT  GETDATE(),
	SITUACAO      CHAR(1) DEFAULT('A')
);

-- DDL CRIANDO TABELA COM CHAVE ESTRANGEIRA
CREATE TABLE SALARIO
(
	MATRICULA INT PRIMARY KEY NOT NULL,
	SALARIO   DECIMAL(10,2) NOT NULL CHECK(SALARIO>0),
	FOREIGN KEY(MATRICULA) REFERENCES COLABORADOR(MATRICULA)
);

-- CORRINDO ERRO PARA CRIAR TABELA SALARIO
-- DDL PARA ADICIONAR CHAVE PRIMARIA NA TAB COLABORADOR
ALTER TABLE COLABORADOR ADD PRIMARY KEY (MATRICULA);

-- DDL CRIAÇÃO DE TABELA COM CHAVE PRIMARIA
CREATE TABLE AUDIT_SALARIO
(
	TRANSACAO  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MATRICULA  INT               NOT NULL,
	DATA_TRANS DATETIME          NOT NULL,
	SAL_ANTIGO DECIMAL(10,2),
	SAL_NOVO   DECIMAL(10,2),
	USUARIO    VARCHAR(20)       NOT NULL
);

-- ADD CHAVE ESTRANGEIRA
ALTER TABLE AUDIT_SALARIO
ADD FOREIGN KEY (MATRICULA) REFERENCES COLABORADOR (MATRICULA);

-- TENTANDO EXCLUIR A TABELAS COLABORADOR 
DROP TABLE COLABORADOR;