-- PARTE 1 CONCEDE - GRANT
-- CRIA UM LOGIN E DÁ PERMISSÕES NO BANCO

USE CURSO;
GO

EXEC MASTER.DBO.SP_ADDLOGIN 'USRTESTE', 'SENHATESTE';

-- ADD
EXEC SP_GRANTDBACCESS 'USRTESTE';

-- EXEC SP_REVOKEDBACCESS 'USRTESTE';

-- CONCEDENDO ACESSO DE ATUALIZAÇÃO PARA USRTESTE
GRANT UPDATE ON FUNCIONARIOS TO USRTESTE;

-- CONCEDENDO ACESSO DE INSERT PARA USRTESTE
GRANT INSERT ON FUNCIONARIOS TO USRTESTE;

-- CONCEDENDO ACESSO DE LEITURA PARA USRTESTE
GRANT SELECT ON FUNCIONARIOS TO USRTESTE;

-- CONCEDENTE ACESSO DE DELETE PARA USRTTESTE
GRANT DELETE ON FUNCIONARIOS TO USRTESTE;

-- CRIANDO PROCEDURE
CREATE PROCEDURE TESTEPROC
AS 
SELECT * FROM SENSO;

-- EXECUTANDO PROCEDURE
EXEC TESTEPROC;

-- CONCEDENDO ACESSO PARA EXECUTAR PROC TESTE_PROC PARA USRTESTE
GRANT EXECUTE ON TESTEPROC TO USRTESTE;