-- PARTE 2 REVOGA - REVOKE
USE curso;
GO

SETUSER;

SELECT CURRENT_USER;

-- REVOGANDO ACESSO DE ATUALIZAÇÃO USRTESTE
REVOKE UPDATE ON FUNCIONARIOS TO USRTESTE;

-- RVOGANDO ACESSO DE INSERÇÃO USRTESTE
REVOKE INSERT ON FUNCIONARIOS TO USRTESTE;

-- REVOGANDO ACESSO DE LEITURA USRTESTE
REVOKE SELECT ON FUNCIONARIOS TO USRTESTE;

-- REVOGANDO DIREITO DE EXECUÇÃO DA PROC TESTE_PROC PARA USRTESTE
REVOKE EXECUTE ON TESTEPROC TO USRTESTE;

-- VERIFICANDO USUÁRIO
SELECT CURRENT_USER;

-- EXEC SP_GRANTDBACCESS 'USRTESTE', 'USRTESTE'

-- EXEC SP_REVOKEDBACCESS 'USRTESTE'

-- ALTERANDO USUÁRIO LOGADO
SETUSER 'USRTESTE';

-- VERIFICANDO USUÁRIO
SELECT CURRENT_USER;

-- EXECUTANTO PROCEDURE COM USUÁRIO USRTESTE
EXEC TESTEPROC;

-- TESTANDO SELECT
SELECT * FROM FUNCIONARIOS;

-- TESTANDO INSERT 
INSERT INTO FUNCIONARIOS VALUES ('Maria', '1000', 'TI');

-- TESTANDO UPDATE
UPDATE FUNCIONARIOS SET NOME = 'Maisa'
WHERE ID = '5';

-- TESTANDO O DELETE
DELETE FROM FUNCIONARIOS
WHERE ID = '5';


SETUSER;

SELECT CURRENT_USER;