-- PARTE 3 NEGA - DENY
USE curso;
GO
-- NEGANDO ACESSO DE ATUALIZAÇÃO USRTESTE
DENY INSERT ON FUNCIONARIOS TO USRTESTE;

-- NEGANDO ACESSO DE INSERÇÃO USRTESTE
DENY SELECT ON FUNCIONARIOS TO USRTESTE;

-- NEGANDO ACESSO DE LEITURA USRTESTE
DENY SELECT ON FUNCIONARIOS TO USRTESTE;

-- NEGANDO ACESSO A EXECUÇÃO DE PROCEDURE
DENY EXECUTE ON TESTEPROC TO USRTESTE;

-- VERIFICANDO USUARIO LOGADO
SELECT CURRENT_USER;

-- ALTERANDO USUARIO LOGADO
SETUSER 'USRTESTE';

-- VERIFICANDO USUARIO LOGADO
SELECT CURRENT_USER;

-- EXECUTANDO PROCEDURE COM USUARIO USRTESTE
EXEC TESTEPROC;

-- TESTANDO SELECT
SELECT * FROM FUNCIONARIOS;

-- TESTANDO INSERT
INSERT INTO FUNCIONARIOS VALUES ('Maria', '1000', 'TI');

-- TESTANDO UPDATE
UPDATE FUNCIONARIOS SET NOME = 'Maisa'
WHERE ID = '5';

-- TESTANDO O DELETE
DELETE FROM FUNCIONARIOS
WHERE ID = '5';

SETUSER;

SELECT CURRENT_USER;