-- CRIANDO DE TESTE
DROP TABLE CADASTRO;
CREATE TABLE CADASTRO
(
NOME  VARCHAR(50) NOT NULL,
DOCTO VARCHAR(20) NOT NULL
);

-- INICIA TRANSAÇÃO
BEGIN TRANSACTION

-- INSERE REGISTROS
INSERT INTO CADASTRO VALUES ('Andre','12341244')
INSERT INTO CADASTRO VALUES ('Joao' ,'12341248')
INSERT INTO CADASTRO VALUES ('Pedro','12341246')

-- SELECT DOS REGISTROS INSERIDOS
SELECT * FROM CADASTRO;

-- RETORNA O TABELA NÃO ESTADO ANTERIOR DO BEGIN TRANSACTION
ROLLBACK

-- EFETIVA AS INFORMAÇÕES NA TABELAS DO BANCO DE DADOS
COMMIT TRANSACTION

-- SELECT DOS REGISTROS INSERIDOS
SELECT * FROM CADASTRO;

