-- LIMPANDO A TABLEA
DELETE FROM CADASTRO;

-- INICIA TRANSA플O
BEGIN TRANSACTION

-- INSERE REGISTRO
INSERT INTO CADASTRO VALUES ('Andre','12341244')

-- CRIA UM PONTO DE RECUPERA플O
SAVE TRANSACTION a1;

-- INSERE REGISTRO
INSERT INTO CADASTRO VALUES ('Joao','12341244')

-- CRIA UM PONTO DE RECUPERA플O
SAVE TRANSACTION a2;

-- INSERE REGISTRO
INSERT INTO CADASTRO VALUES ('Pedro','12341244')

-- CRIA UM PONTO DE RECUPERA플O
SAVE TRANSACTION a3;

-- VERIFICA REGITROS
SELECT * FROM CADASTRO;

-- REDTAURA A TABELA ATE O PONTO a2
ROLLBACK TRANSACTION a2

-- VERIFICA REGISTROS
SELECT * FROM CADASTRO;

-- RETORNA O TABELA N홒 ESTADO ANTERIOR DO BEGIN TRANSACTION
ROLLBACK

-- EFETIVA AS INFORMA합ES NA TABELAS DO BANCO DE DADOS
COMMIT TRANSACTION

-- SELECT DOS REGISTROS INSERIDOS
SELECT * FROM CADASTRO;