-- SUBQUERYS
USE crm

--EXEMPLOS SUBQUERYS
SELECT A.ID_CLIENTE,
	   A.PRIMEIRO_NOME,
	   A.ULTIMO_NOME,
	   A.SEXO
FROM cliente A
WHERE A.ID_CLIENTE IN 
(SELECT B.ID_CLIENTE
FROM CARRO_CLIENTE B
WHERE B.ANO = '2005');

--EXEMPLOS SUBQUERYS
SELECT A.ID_CLIENTE,
	   A.PRIMEIRO_NOME,
	   A.ULTIMO_NOME,
	   A.SEXO
FROM cliente A
WHERE A.ID_CLIENTE IN 
(SELECT B.ID_CLIENTE
FROM CARRO_CLIENTE B
WHERE B.ANO = '2005'
AND B.ID_CARRO IN 
(SELECT C.ID_CARRO
FROM CARRO_MONTADORA C
WHERE C.ID_MONTADORA = 2));


-- RETORNANDO O NOME DO CARRO COM SUBQUERY
SELECT A.ID_CLIENTE,
	   A.PRIMEIRO_NOME,
	   A.ULTIMO_NOME,
	   A.SEXO,
	   (SELECT B.NOME_CARRO
	   FROM CARRO_MONTADORA B
	   INNER JOIN CARRO_CLIENTE C
	   ON B.ID_CARRO = C.ID_CARRO
	   AND A.ID_CLIENTE = C.ID_CLIENTE) AS NOME_CARRO
FROM CLIENTE A;


-- RETORNANDO O PAIS COM SUBQUERY
SELECT A.ID_CLIENTE,
	   A.PRIMEIRO_NOME,
	   A.ULTIMO_NOME,
	   A.CODIGO_PAIS,
	   (SELECT B.NOME_PAIS
	    FROM PAIS B
		WHERE A.CODIGO_PAIS = B.CODIGO_PAIS) AS NOME_PAIS
FROM CLIENTE A


-- RETORNANDO O PAIS E O IDIOMA COM SUBQUERY
SELECT A.ID_CLIENTE,
	   A.PRIMEIRO_NOME,
	   A.ULTIMO_NOME,
	   A.CODIGO_PAIS,
	   (SELECT B.NOME_PAIS
	    FROM PAIS B
		WHERE A.CODIGO_PAIS = B.CODIGO_PAIS) AS NOME_PAIS,
	   (SELECT TOP 1 B.IDIOMA
	    FROM IDIOMAS B
		WHERE A.ID_CLIENTE = B.ID_CLIENTE) AS IDIOMA
FROM CLIENTE A

-- SUBQUERYS COM FUNÇÕES DE AGREGAÇÃO
SELECT A.ID_MONTADORA,
	   A.NOME_CARRO,
	   (SELECT AVG(B.ANO)
	    FROM CARRO_CLIENTE B
		WHERE A.ID_CARRO = B.ID_CARRO) AS MEDIA_ANO,
	   (SELECT MIN(B.ANO)
	    FROM CARRO_CLIENTE B
		WHERE A.ID_CARRO = B.ID_CARRO) AS MAIS_ANTIGO,
	   (SELECT MAX(B.ANO)
	    FROM CARRO_CLIENTE B
		WHERE A.ID_CARRO = B.ID_CARRO) AS MAIS_NOVO,
	   (SELECT COUNT(*)
	    FROM CARRO_CLIENTE B
		WHERE A.ID_CARRO = B.ID_CARRO) AS QTD
FROM CARRO_MONTADORA A

-- CRIANDO UM CENARIO PARA FAZER UM UPDATE COM SUBSELECT
ALTER TABLE CARRO_MONTADORA ADD QDT INT;

--VERIFICANDO INFORMAÇÃO DA TABELA
SELECT * FROM CARRO_MONTADORA;

-- CRIANDO UPDATE PARA CONTAR QTD DE CARROS QUE OS CLIENTES POSSUEM MEDELO
BEGIN TRANSACTION
 UPDATE CARRO_MONTADORA SET QDT = (
								  SELECT COUNT(*) AS QTD FROM CARRO_CLIENTE B
								  INNER JOIN CARRO_MONTADORA C
								  ON C.ID_CARRO = B.ID_CARRO
								  AND CARRO_MONTADORA.ID_CARRO = B.ID_CARRO
								  GROUP BY B.ID_CARRO
								  );
-- SE CORRETO COMMIT
COMMIT;

-- ERRO ROLLBACK
ROLLBACK;

--DROP COLUNA 
ALTER TABLE CARRO_MONTADORA DROP COLUMN QDT;

--EXEMPLO DE DELETE COM SUBQUERY

BEGIN TRANSACTION 

DELETE CARRO_CLIENTE
WHERE ID_CLIENTE IN
	              (SELECT ID_CLIENTE
				   FROM CLIENTE 
				   WHERE CODIGO_PAIS = 'BR');

ROLLBACK

SELECT * FROM CARRO_CLIENTE;