-- JOINS - PARTE 1
USE curso;
-- DROP TABLE ALUNOS
-- CRIAÇÃO DE TABELAS ALUNOS
-- DROP TABLE ALUNOS
-- DROP TABLE DISCIPLINA
-- DROP TABLE MATRICULA

CREATE TABLE ALUNOS
(
ID_ALUNO INT IDENTITY(1, 1),
NOME VARCHAR(20) NOT NULL
);

-- DROP TABLE DISCIPLINA
CREATE TABLE DISCIPLINA
(
ID_DISCIPLINA INT IDENTITY(1, 1),
NOME_DISC VARCHAR(20)
);

-- DROP TABLE MATRICULA
CREATE TABLE MATRICULA
(
ID_ALUNO INT,
ID_DISCIPLINA INT,
PERIODO VARCHAR(10)
);

-- ALTERANDO TABELA CAMPO ID_ALUNO PARA NÃO PERMITIR NOT NULL
ALTER TABLE MATRICULA ALTER COLUMN ID_ALUNO INT NOT NULL;

-- ALTERANDO TABELA 
ALTER TABLE MATRICULA ALTER COLUMN ID_DISCIPLINA INT NOT NULL;

-- CRIANDO CHAVE PRIMARIA COMPOSTA
ALTER TABLE MATRICULA ADD CONSTRAINT PK_1 PRIMARY KEY (ID_ALUNO, ID_DISCIPLINA);

-- ADICIONANDO CHAVE PRIMARIA TABELA DISCIPLINA
ALTER TABLE DISCIPLINA ADD CONSTRAINT PK2 PRIMARY KEY (ID_DISCIPLINA);

-- ADICIONANDO CHAVE PRIMARIA TABELA ALUNOS
ALTER TABLE ALUNOS ADD CONSTRAINT PK1 PRIMARY KEY (ID_ALUNO);

-- ADICIONANDO CHAVE ESTRAGEIRA NA TABELA MATRICULA CAMPO ID_ALUNO
ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MAT1 FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO)

-- ADICIONANDO CHAVE ESTRANGEIRA NA TABELA MATRICULA CAMPO ID_ALUNO
ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MAT2 FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID_DISCIPLINA);

-- INSERINDO REGISTROS ALUNOS
INSERT INTO ALUNOS VALUES ('JOAO'),('MARIA'),('TIAGO'),('HENRIQUE');

SELECT * FROM ALUNOS;

-- INSERINDO REGISTRO DISCIPLINAS
INSERT INTO DISCIPLINA VALUES
('FISICA'), ('QUIMICA'), ('MATEMATICA'), ('BANCO DE DADOS'), ('PROGRAMACAO');

SELECT * FROM DISCIPLINA;

-- INSERINDO MATRICULAS DE ALUNOS
INSERT INTO MATRICULA VALUES('1', '1', 'NOTURNO');
INSERT INTO MATRICULA VALUES('1', '2', 'VESPERTINO');
INSERT INTO MATRICULA VALUES('1', '3', 'MATUTINO');

INSERT INTO MATRICULA VALUES('2', '3', 'NOTURNO');
INSERT INTO MATRICULA VALUES('2', '4', 'NOTURNO');

INSERT INTO MATRICULA VALUES('3', '1', 'NOTURNO');
INSERT INTO MATRICULA VALUES('3', '3', 'NOTURNO');
INSERT INTO MATRICULA VALUES('3', '4', 'NOTURNO');

INSERT INTO MATRICULA VALUES('5', '1', 'MATUTINO');
INSERT INTO MATRICULA VALUES('5', '2', 'VESPERTINO');
INSERT INTO MATRICULA VALUES('5', '4', 'NOTURNO');

-- SIMULANDO ERROS
INSERT INTO MATRICULA VALUES ('6', '6', 'NOTURNO');

INSERT INTO MATRICULA VALUES ('5', '4', 'NOTURNO');

-- ALUNO CODIGO 4 NAO TEM MATRICULA
-- DISCIPLINA 5 NAO TEM ALUNOS

-- INNER JOIN
SELECT A.ID_ALUNO,
	   A.NOME,
	   C.ID_DISCIPLINA,
	   C.NOME_DISC,
	   B.PERIODO
FROM ALUNOS A
INNER JOIN MATRICULA B
ON A.ID_ALUNO = B.ID_ALUNO
INNER JOIN DISCIPLINA C
ON B.ID_DISCIPLINA = C.ID_DISCIPLINA;

-- LEFT JOIN
SELECT A.ID_ALUNO,
	   A.NOME,
	   C.ID_DISCIPLINA,
	   C.NOME_DISC,
	   B.PERIODO
FROM ALUNOS A
LEFT JOIN MATRICULA B
ON A.ID_ALUNO = B.ID_ALUNO
LEFT JOIN DISCIPLINA C
ON B.ID_DISCIPLINA = C.ID_DISCIPLINA;

-- RIGHT JOIN
SELECT A.ID_ALUNO,
	   A.NOME,
	   C.ID_DISCIPLINA,
	   C.NOME_DISC,
	   B.PERIODO
FROM ALUNOS A
RIGHT JOIN MATRICULA B
ON A.ID_ALUNO = B.ID_ALUNO
RIGHT JOIN DISCIPLINA C
ON B.ID_DISCIPLINA = C.ID_DISCIPLINA
ORDER BY A.ID_ALUNO ASC;

-- FULL JOIN
SELECT A.ID_ALUNO,
	   A.NOME,
	   C.ID_DISCIPLINA,
	   C.NOME_DISC,
	   B.PERIODO
FROM ALUNOS A
FULL JOIN MATRICULA B
ON A.ID_ALUNO = B.ID_ALUNO
FULL JOIN DISCIPLINA C
ON B.ID_DISCIPLINA = C.ID_DISCIPLINA;
