-- INNER JOIN
-- TESTANDO SEUS CONHECIMENTOS
USE crm;

SELECT A.ID_CLIENTE,
	   A.PRIMEIRO_NOME,
	   A.CODIGO_PAIS,
	   B.ANO,
	   C.NOME_CARRO,
	   D.NOME_MONTADORA
FROM CLIENTE A 
INNER JOIN CARRO_CLIENTE B
ON A.ID_CLIENTE = B.ID_CLIENTE

INNER JOIN CARRO_MONTADORA C
ON B.ID_CARRO = C.ID_CARRO 

INNER JOIN MONTADORA D 
ON C.ID_MONTADORA = D.ID_MONTADORA;

-- INNER JOIN
USE AdventureWorks2017;

SELECT A.BUSINESSENTITYID,
	   A.FIRSTNAME,
	   A.LASTNAME,
	   B.JOBTITLE,
	   A.PERSONTYPE
FROM PERSON.PERSON A
INNER JOIN HUMANRESOURCES.EMPLOYEE B
ON A.BUSINESSENTITYID = B.BUSINESSENTITYID

-- VERIFICANDO DADOS TABELA PERSON
SELECT * FROM PERSON.PERSON;

-- RIGTH JOIN
SELECT A.BUSINESSENTITYID,
	   A.FIRSTNAME,
	   A.LASTNAME,
	   B.JOBTITLE,
	   A.PERSONTYPE
FROM PERSON.PERSON A
RIGHT JOIN HUMANRESOURCES.EMPLOYEE B
ON A.BUSINESSENTITYID = B.BUSINESSENTITYID

-- LEFT JOIN
SELECT A.BUSINESSENTITYID,
	   A.FIRSTNAME,
	   A.LASTNAME,
	   B.JOBTITLE,
	   A.PERSONTYPE
FROM PERSON.PERSON A
LEFT JOIN HUMANRESOURCES.EMPLOYEE B
ON A.BUSINESSENTITYID = B.BUSINESSENTITYID

-- FULL JOIN
SELECT A.BUSINESSENTITYID,
	   A.FIRSTNAME,
	   A.LASTNAME,
	   B.JOBTITLE,
	   A.PERSONTYPE
FROM PERSON.PERSON A
FULL JOIN HUMANRESOURCES.EMPLOYEE B
ON A.BUSINESSENTITYID = B.BUSINESSENTITYID