-- CONHECENDO AS TABELAS
USE CURSO;

SELECT TOP 5 * FROM SENSO;
SELECT TOP 5 * FROM UF;
SELECT TOP 5 * FROM REGIAO;

-- AVG RETORNA A MÉDIA DOS VALORES EM UM GROUPO. VALORES NULOS SÃO IGNORADOS
SELECT AVG(POPULACAO) FROM SENSO;

-- AVG MEDIA POR ESTADO

SELECT UF, AVG(POPULACAO) AS QTD FROM SENSO
GROUP BY UF
ORDER BY 2 DESC;

-- AVG POR REGIÃO
SELECT B.REGIAO,
	   AVG(A.POPULACAO)
FROM SENSO A
INNER JOIN REGIAO B
ON A.COD_UF = B.COD_UF
GROUP BY B.REGIAO
ORDER BY 2 DESC;

-- MIN RETORNA O VALOR MINIMO NA EXPRESSAO. PODE SER SEGUIDO PELA CLÁUSULA OVER
SELECT MIN(POPULACAO) FROM SENSO;

-- MIN POR ESTADO
SELECT UF,
	   MIN(POPULACAO)
FROM SENSO
GROUP BY UF
ORDER BY 2 DESC;

-- MIN POR REGIAO
SELECT B.REGIAO,
	   MIN(POPULACAO)
FROM SENSO A
INNER JOIN REGIAO B
ON A.COD_UF = B.COD_UF
GROUP BY B.REGIAO
ORDER BY 2 DESC;


-- MAX RETORNA O VALOR MAXIMO NA EXPRESSAO
SELECT MAX(POPULACAO) FROM SENSO;

-- MAX POR ESTADO
SELECT UF,
	   MAX(POPULACAO)
FROM SENSO
GROUP BY UF
ORDER BY 2 DESC;

-- MAX POR REGIAO
SELECT B.REGIAO,
	   MAX(A.POPULACAO) AS MAXIMO
FROM SENSO A
INNER JOIN REGIAO B
ON A.COD_UF = B.COD_UF
GROUP BY B.REGIAO
ORDER BY 2 DESC;

-- SUM RETORNA A SOMA DE TODOS OS VALORES OU SOMENTE OS VALORES DISTINCT NA EXPRESSAO.
-- SUM PODE SER USADO EXCLUSIVAMENTE COM COLUNAS NUMERICAS. VALORES NULOS SAO IGNORADOS.

SELECT SUM(POPULACAO) FROM SENSO;

-- SUM POR ESTADO
SELECT UF,
	   SUM(POPULACAO)
FROM SENSO
GROUP BY UF
ORDER BY 2 DESC;

-- SUM POR REGIAO
SELECT B.REGIAO,
	   SUM(A.POPULACAO)
FROM SENSO A
INNER JOIN REGIAO B
ON A.COD_UF = B.COD_UF
GROUP BY B.REGIAO
ORDER BY 2 DESC;

-- COUNT RETORNA O NUMERO DE ITENS DE UM GROUPO
SELECT COUNT(*) FROM SENSO;

-- DESCOBRINDO QTD ESTADOS
SELECT COUNT(DISTINCT UF) FROM SENSO;

-- EXEMPLO
SELECT COUNT(UF) FROM SENSO;

-- COUNT POR ESTADO
SELECT UF,
	   COUNT(*) AS QTD 
FROM SENSO
GROUP BY UF 
ORDER BY 2 DESC;

-- COUNT POR REGIAO
SELECT B.REGIAO,
	   COUNT(*) AS QTD
FROM SENSO A
INNER JOIN REGIAO B
ON A.COD_UF = B.COD_UF
GROUP BY B.REGIAO
ORDER BY 2 DESC;

-- USANDO VARIAS FUNCOES DE AGREGACAO
SELECT AVG(POPULACAO) AS MEDIA_POP,
	   MIN(POPULACAO) AS MINIMO_POP,
	   MAX(POPULACAO) AS MAXIMO_POP,
	   SUM(POPULACAO) AS TOTAL_POP,
	   COUNT(*)       AS QTD_CIDADES
FROM SENSO;

