-- CONTINUAÇÃO

USE curso;

-- POR ESTADO

SELECT UF,
	   AVG(POPULACAO) AS MEDIA_POP,
	   MIN(POPULACAO) AS MINIMO_POP,
	   MAX(POPULACAO) AS MAXIMO_POP,
	   SUM(POPULACAO) AS TOTAL_POP,
	   COUNT(*) AS QTD_CIDADES
FROM senso
GROUP BY UF
ORDER BY 1 DESC;

-- POR REGIAO

SELECT B.REGIAO,
	   AVG(POPULACAO) AS MEDIA_POP,
	   MIN(POPULACAO) AS MINIMO_POP,
	   MAX(POPULACAO) AS MAXIMO_POP,
	   SUM(POPULACAO) AS TOTAL_POP,
	   COUNT(*) AS QTD_CIDADES
FROM senso A
INNER JOIN REGIAO B
ON A.COD_UF = B.cod_uf
GROUP BY REGIAO
ORDER BY 2 DESC;

-- STDEV RETORNA O DESVIO PADRAO ESTATISTICO DE TODOS OS VALORES DA EXPRESSÃO ESPECÍFICADA

SELECT STDEV(POPULACAO) FROM SENSO;

-- STDEVP RETORNA O DESVIO PADRAO ESTATISTICO PARA A POPULAÇÃO DE TODOS OS
-- VALORES NA EXPRESSÃO ESPECÍFICADA

SELECT STDEVP(POPULACAO) FROM SENSO;

-- GROUPING INDICA SE UMA EXPRESSÃO DE COLUNA ESPECIFICADA EM UMA LISTA
-- GROUP BY É AGREGADA OU NAO. GROUPING RETORNA 1 PARA AGREGADA OU 0 
-- PARA NÃO AGREGADA NO CONJUNTO DE RESULTADOS

SELECT UF,
	   SUM(POPULACAO) AS POPULACAO,
	   GROUPING(UF) AS GRUPO
FROM SENSO
GROUP BY UF WITH ROLLUP;

-- PROJETANDO CRESCIMENTO USANDO EXEMPLO
SELECT A.NOME_MUN,
       A.POPULACAO,
	   A.POPULACAO * 1.05 AS PROJECAO_POP
FROM SENSO A

-- POR ESTADO
SELECT A.UF,
	   SUM(A.POPULACAO) AS POPULACAO,
	   SUM(A.POPULACAO) * 1.05 AS PROJECAO_POP
FROM SENSO A
GROUP BY A.UF;

-- GROUPING_ID
/*
É UMA FUNÇÃO QUE CALCULA O NÍVEL DE AGRUPAMENTO.
GROUPING_ID PODE SER USADA APENAS NA LISTA SELECT <SELECT>
NA CLÁSULA HAVING OU ORDER BY, QUANDO GROUP BY FOR ESPECIFICADA.
*/

SELECT B.REGIAO,
	   A.UF,
	   SUM(A.POPULACAO) AS POPULACAO,
	   GROUPING_ID(B.REGIAO, A.UF) AS GRUPO
FROM SENSO A
INNER JOIN REGIAO B
ON A.COD_UF = B.COD_UF
GROUP BY ROLLUP(B.REGIAO, A.UF);

-- VAR RETORNA A VARIANCIA ESTATISTICA DE TODOS OS VALORES DA EXPRESSAO ESPECIFICADA
SELECT VAR(POPULACAO) FROM SENSO;

SELECT UF,
	   VAR(POPULACAO)
FROM SENSO
GROUP BY UF;

-- VARP RETORNA A VARIANCIA ESTATISTICA PARA O PREENCHIMENTO
-- DE TODOS OS VALORES DA EXPRESSAO ESPECIFICADA
SELECT VARP(POPULACAO) FROM SENSO
GROUP BY UF;

SELECT UF,
	   VAR(POPULACAO) AS var,
	   VARP(POPULACAO) AS varp
FROM SENSO
GROUP BY UF;

-- EXEMPLO COM GROUPING
USE CRM;

SELECT CODIGO_PAIS,
	   COUNT(*) AS 'QTD',
	   GROUPING(CODIGO_PAIS) AS 'GROUPING'
FROM CLIENTE
GROUP BY CODIGO_PAIS WITH ROLLUP;

-- EXEMPLO
SELECT A.NOME_MONTADORA,
	   COUNT(*)AS 'QTD',
	   GROUPING(A.NOME_MONTADORA) AS 'GROUPING'
FROM MONTADORA A 
INNER JOIN CARRO_MONTADORA B
ON A.ID_MONTADORA = B.ID_MONTADORA
GROUP BY A.NOME_MONTADORA WITH ROLLUP;

-- EXEMPLO 
SELECT A.NOME_MONTADORA,
       B.NOME_CARRO,
	   COUNT(*) AS 'QTD',
	   GROUPING(A.NOME_MONTADORA) AS 'GROUPING'
FROM MONTADORA A 
INNER JOIN CARRO_MONTADORA B
ON A.ID_MONTADORA = B.ID_MONTADORA
WHERE A.NOME_MONTADORA IN ('TOYOTA', 'ALFA ROMEO')
GROUP BY A.NOME_MONTADORA,
	     B.NOME_CARRO 
WITH ROLLUP;

-- TRAZENDO O NOME CIDADE COM MAIOR PUPULACAO EM CADA ESTADO
USE CURSO;

SELECT A. * FROM
	  (SELECT COD_UF,
	          MAX(POPULACAO) AS POPULACAO
	    FROM SENSO
        GROUP BY COD_UF) B
JOIN SENSO A
ON A.COD_UF = B.COD_UF
AND A.POPULACAO = B.POPULACAO
ORDER BY A.POPULACAO DESC;

SELECT A. * FROM
	  (SELECT COD_UF,
	          MIN(POPULACAO) AS POPULACAO
	    FROM SENSO
        GROUP BY COD_UF) B
JOIN SENSO A
ON A.COD_UF = B.COD_UF
AND A.POPULACAO = B.POPULACAO
ORDER BY A.POPULACAO DESC;

-- OUTRO EXEMPLO
SELECT A.COD_UF,
	   A.NOME_MUN,
	   A.POPULACAO
FROM SENSO A
GROUP BY A.COD_UF,
         A.NOME_MUN,
		 A.POPULACAO
HAVING POPULACAO = (
	                 SELECT MAX(POPULACAO) 
					 FROM SENSO
					 WHERE COD_UF = A.COD_UF
					 )
ORDER BY A.POPULACAO DESC;

SELECT A.COD_UF,
	   A.NOME_MUN,
	   A.POPULACAO
FROM SENSO A
GROUP BY A.COD_UF,
         A.NOME_MUN,
		 A.POPULACAO
HAVING POPULACAO = (
	                 SELECT MIN(POPULACAO) 
					 FROM SENSO
					 WHERE COD_UF = A.COD_UF
					 )
ORDER BY A.POPULACAO DESC;


