-- RANK EXEMPLO 1
/*
AS FUNÇÕES DE CLASSIFICAÇÃO RETORNAM UM VALOR DE CLASIFICAÇÃO
PARA CADA LINHA EM UMA PARTIÇÃO. DEPENDENDO DA FUNÇÃO USADA,
ALGUMAS LINHAS PODEM RECEBER O MESMO VALOR QUE OUTRAS.
AS FUNÇÕES DE CLASSIFICAÇÃO SÃO NÃO DETERMINÍSTICAS
*/

USE CURSO;

SELECT RANK() OVER(ORDER BY ESTADO ASC) AS RANK_UF,
	   ESTADO
FROM UF;

-- RANK EXEMPLO 2
SELECT RANK() OVER (ORDER BY ESTADO ASC) AS RANK_UF,
	   REGIAO,
	   ESTADO
FROM REGIAO;

-- RANK EXEMPLO 3
SELECT RANK() OVER (ORDER BY REGIAO ASC) AS RANK_UF,
	   REGIAO,
	   ESTADO
FROM REGIAO;

--NTILE
/*
DISTRIBUI AS LINHAS DE UMA PARTIÇÃO ORDENADA EM UM NÚMERO DE GRUPOS ESPECIFICADO.
OS GRUPOS SÃO NUMERADOS, INICIANDO EM UM. PARA CADA LINHA, 
NTILE RETORNA O NÚMERO DO GRUPO AO QUAL A LINHA PERTENCE
*/

SELECT NTILE(4) OVER (ORDER BY REGIAO ASC) AS NTILE_UF,
	   REGIAO,
	   ESTADO
FROM REGIAO;

-- DENSE_RANK
/*
RETRONA A CLASSIFICAÇÃO DE LINHAS DENTRO DA PARTIÇÃO DE UM CONJUNTO DE RESULTADOS,
SEM QUALQUER LACUNA NA CLASSIFICAÇÃO. A CLASSIFICAÇÃO DE UMA LINHA É UM MAIS
O NÚMERO DE CLASSFICAÇÕES DISTINTAS QUE VÊM ANTES DA LINHA EM QUESTÃO.
*/

SELECT DENSE_RANK() OVER (ORDER BY REGIAO ASC) AS DENSE_RANK_UF,
	   REGIAO,
	   ESTADO
FROM REGIAO;

SELECT DENSE_RANK() OVER (ORDER BY ESTADO ASC) AS DENSE_RANK_UF,
	   REGIAO,
	   ESTADO REGIAO_UF
FROM REGIAO;

-- ROW_NUMBER
/*
RETORNA O NÚMERO SEQUENCIAL DE UMA LINHA EM UMA PARTIÇÃO DE UM CONJUNTO DE RESULTADOS,
INICIANDO EM 1 PARA A PRIMEIRA LINHA DE CADA PARIÇÃO.
*/

SELECT ROW_NUMBER() OVER (ORDER BY ESTADO ASC) AS ROW_NUMBER_UF,
	   REGIAO,
	   ESTADO
FROM REGIAO;

-- COMBINANDO VALORES 1
SELECT ROW_NUMBER() OVER (ORDER BY REGIAO ASC) AS ROW_NUMBER_UF,
	   DENSE_RANK() OVER (ORDER BY REGIAO ASC) AS DENSE_RANK_UF,
	   NTILE(6)      OVER (ORDER BY REGIAO ASC) AS NTILE_UF,
	   RANK()       OVER (ORDER BY REGIAO ASC) AS RANK_UF,
	   REGIAO,
	   ESTADO REGIAO_UF
FROM REGIAO
ORDER BY 5,6;

SELECT ROW_NUMBER() OVER (ORDER BY REGIAO ASC) AS ROW_NUMBER_UF,
	   DENSE_RANK() OVER (ORDER BY REGIAO ASC) AS DENSE_RANK_UF,
	   NTILE(5)      OVER (ORDER BY REGIAO ASC) AS NTILE_UF,
	   RANK()       OVER (ORDER BY REGIAO ASC) AS RANK_UF,
	   REGIAO,
	   ESTADO REGIAO_UF
FROM REGIAO
ORDER BY 4,6;

-- SIMULANDO CLASSFICAÇÃO DE CAMPEONATO
-- DROP TABLE CAMPEONATO

CREATE TABLE CAMPEONATO
(
NOMETIME VARCHAR(30) NOT NULL,
PONTOS INT NOT NULL
);

-- POPULANDO TABELA
INSERT INTO CAMPEONATO VALUES ('ATLÉTICO-GO','22');
INSERT INTO CAMPEONATO VALUES ('CHAPECOENSE','28');
INSERT INTO CAMPEONATO VALUES ('PONTE PRETA','28');
INSERT INTO CAMPEONATO VALUES ('GRÊMIO','43');
INSERT INTO CAMPEONATO VALUES ('CRUZEIRO','37');
INSERT INTO CAMPEONATO VALUES ('SANTOS','41');
INSERT INTO CAMPEONATO VALUES ('PALMEIRAS','40');
INSERT INTO CAMPEONATO VALUES ('CORINTHIANS','53');
INSERT INTO CAMPEONATO VALUES ('FLAMENGO','38');
INSERT INTO CAMPEONATO VALUES ('BOTAFOGO','37');
INSERT INTO CAMPEONATO VALUES ('ATLÉTICO-PR','34');
INSERT INTO CAMPEONATO VALUES ('VASCO','31');
INSERT INTO CAMPEONATO VALUES ('ATLÉTICO-MG','31');
INSERT INTO CAMPEONATO VALUES ('SPORT','29');
INSERT INTO CAMPEONATO VALUES ('AVAÍ','29');
INSERT INTO CAMPEONATO VALUES ('BAHIA','27');
INSERT INTO CAMPEONATO VALUES ('FLUMINENSE','31');
INSERT INTO CAMPEONATO VALUES ('SÃO PAULO','27');
INSERT INTO CAMPEONATO VALUES ('CORITIBA','27');
INSERT INTO CAMPEONATO VALUES ('VITÓRIA','26');

SELECT * FROM CAMPEONATO;

-- CLASSIFICAÇÃO DE CAMPEONATO
SELECT RANK() OVER (ORDER BY PONTOS DESC) AS CLASSIF,
       NOMETIME,
	   PONTOS
FROM CAMPEONATO;