-- CHOOSE: RETORNA O ITEM AO ÍNDICE ESPECIFICADO DE UMA LISTA
-- DE VALORES NO SQL SERVER

-- EXEMPLO 1

SELECT CHOOSE (3, 'GERENTE', 'DIRETOR', 'DESENVOLVEDOR', 'TESTER') AS ESCOLHIDO

-- EXEMPLO 2
USE AdventureWorks2017

SELECT DISTINCT PRODUCTCATEGORYID FROM PRODUCTION.PRODUCTCATEGORY;

SELECT PRODUCTCATEGORYID,
       CHOOSE(PRODUCTCATEGORYID, 'A', 'B', 'C', 'D', 'E') AS EXPRESSAO
FROM PRODUCTION.PRODUCTCATEGORY;

-- EXEMPLO 3

SELECT JOBTITLE,
       HIREDATE,
       MONTH(HIREDATE) AS MES,
       CHOOSE(MONTH(HIREDATE), 'WINTER', 'WINTER', 'SPRING', 'SPRING',
                               'SPRING', 'SUMMER', 'SUMMER', 'SUMMER',
                               'AUTUMN', 'AUTUMN', 'AUTUMN', 'WINTER') AS QUARTER_HIRED
FROM HUMANRESOURCES.EMPLOYEE
WHERE YEAR(HIREDATE) > 2005
ORDER BY YEAR(HIREDATE);

-- IIF: RETORNA UM DE DOIS VALORES, DEPENDENDO DE A EXPRESSAO BOOLIANA
-- SER AVALIADA COMO TRUE OU FALSE NO SQL SERVER

-- EXEMPLO 1
DECLARE @A INT = 45,
        @B INT = 40;
        SELECT IIF(@A > @B, 'TRUE', 'FALSE') AS RESULTADO;


DECLARE @A INT = 45,
        @B INT = 40;
        SELECT IIF(@A > @B, 'MAIOR', 'MENOR') AS RESULTADO;

DECLARE @A INT = 45,
        @B INT = 40;
        SELECT IIF(@A < @B, 'MENOR', 'MAIOR') AS RESULTADO;

-- EXEMPLO 2
-- IIF COM CONSTANTE NULL
-- O RESULTADO DESSA INSTRUÇÃO É UM ERRO

SELECT IIF(45 > 30, NULL, NULL) AS RESULT;

-- EXEMPLO 3
/*
IIF COM PARÂMETROS NULL
O RETORNO NULL.
*/
DECLARE @P INT = NULL,
        @S INT = NULL;
        SELECT IIF(45 > 30, @P, @S) AS RESULTADO;
